# depends on docker-compose-shared.yml

version: "3.8"
services:
  console:
    image: docker.redpanda.com/vectorized/console
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["broker:29092"]
          schemaRegistry:
            enabled: true
            urls: ["http://broker:8081"]
    ports:
      - "8080:8080"
    depends_on:
      - broker
