# Share components (middlewares)
version: "3.8"

services:
  broker:
    # NB: do not use v22 since redpanda.auto_create_topics_enabled is not supported
    # cf https://cwiki.apache.org/confluence/display/KAFKA/KIP-487%3A+Client-side+Automatic+Topic+Creation+on+Producer
    # also for more thoughts about this option even in Kafka
    image: docker.vectorized.io/vectorized/redpanda:v21.11.19
    container_name: broker
    command:
      - redpanda start
      - --smp 1
      - --reserve 0M
      - --overprovisioned
      - --node-id 0
      - --set redpanda.auto_create_topics_enabled=true
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://broker:29092,OUTSIDE://localhost:9092
    ports:
      - 9092:9092
      - 29092:29092

  minio:
    hostname: minio
    image: 'minio/minio:RELEASE.2021-01-08T21-18-21Z'
    container_name: minio
    ports:
      - '9000:9000'
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: password
    command: server /data

  hydra-postgres:
    build:
      context: .
      dockerfile: dockerfiles/hydra/Dockerfile.hydra.postgres
    container_name: hydra-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  hydra-redis:
    image: redis:latest
    container_name: hydra-redis
    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6380"]

  analysis-redis:
    image: redis:latest
    container_name: analysis-redis
    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6380"]
